name: Sync to Gitee

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitee
        run: |
          git push "https://${{ secrets.GITEE_TOKEN }}@gitee.com/vureact-js/core.git" ${{ github.ref_name }} -f --tags
